"""Seed SQLite with demo data from the original static site."""
import json
from db import init_db, db_cursor, DB_PATH
import os

# Minimal reliable image URLs
IMG = {
    "rice": "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    "cook": "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80",
    "beach": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    "weave": "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=800&q=80",
    "mountain": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80",
    "dinner": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    "temple": "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80",
    "craft": "https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=800&q=80",
    "kayak": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80",
    "market": "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
    "india1": "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80",
    "india2": "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80",
    "india3": "https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800&q=80",
    "forest": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    "japan": "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    "foodjp": "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800&q=80",
    "mexico": "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=800&q=80",
    "textile": "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&q=80",
    "morocco": "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800&q=80",
    "atlas": "https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=800&q=80",
    "peru": "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80",
    "lima": "https://images.unsplash.com/photo-1531968452301-4f2f5c0f345b?w=800&q=80",
    "tuscany": "https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800&q=80",
    "thailand": "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80",
    "person1": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    "person2": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    "person3": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80",
    "person4": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80",
    "person5": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80",
    "person6": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&q=80",
}

GUIDES = [
    {"id": "g1", "name": "Made Wijaya", "photo": IMG["person1"], "country": "Indonesia", "city": "Ubud",
     "languages": ["English", "Indonesian"], "specialties": ["Nature", "Rice fields", "Culture"],
     "bio": "Third-generation farmer-guide. Shows the quiet side of Bali and keeps income in his village.",
     "price_per_hour": 12, "phone": "+62 812-3456-1001", "rating": 4.9, "reviews": 87, "verified": 1,
     "earnings_note": "Earns from walk & farm experiences", "experiences": ["exp-1", "exp-7"]},
    {"id": "g2", "name": "Ni Wayan Sari", "photo": IMG["person2"], "country": "Indonesia", "city": "Ubud",
     "languages": ["Indonesian", "English"], "specialties": ["Cooking", "Culture", "Family"],
     "bio": "Home kitchen host. Shares family recipes and market stories with small groups.",
     "price_per_hour": 15, "phone": "+62 812-3456-1002", "rating": 4.95, "reviews": 64, "verified": 1,
     "earnings_note": "Cooking classes & market tours", "experiences": ["exp-2", "exp-8"]},
    {"id": "g3", "name": "Rajesh Kumar", "photo": IMG["person3"], "country": "India", "city": "Rishikesh",
     "languages": ["Hindi", "English"], "specialties": ["Yoga", "Ganges", "Nature"],
     "bio": "Local yoga & river host focused on peaceful mornings away from main tourist strips.",
     "price_per_hour": 10, "phone": "+91 98765-43210", "rating": 4.85, "reviews": 112, "verified": 1,
     "earnings_note": "Sunrise walks & quiet practice", "experiences": ["exp-4", "exp-5"]},
    {"id": "g4", "name": "Priya Sharma", "photo": IMG["person4"], "country": "India", "city": "Jaipur region",
     "languages": ["Hindi", "English", "Rajasthani"], "specialties": ["Crafts", "Textiles", "Villages"],
     "bio": "Connects travelers with artisan families so income stays with makers.",
     "price_per_hour": 14, "phone": "+91 98765-43211", "rating": 4.9, "reviews": 58, "verified": 1,
     "earnings_note": "Village craft days", "experiences": ["exp-6", "exp-19"]},
    {"id": "g5", "name": "Yuki Tanaka", "photo": IMG["person5"], "country": "Japan", "city": "Kyoto outskirts",
     "languages": ["Japanese", "English"], "specialties": ["Temples", "Gardens", "Quiet paths"],
     "bio": "Soft-spoken local who prefers lesser-known paths and early temple visits.",
     "price_per_hour": 28, "phone": "+81 90-1234-5678", "rating": 4.95, "reviews": 41, "verified": 1,
     "earnings_note": "Garden walks & tea", "experiences": ["exp-10", "exp-11"]},
    {"id": "g6", "name": "Carlos Mendoza", "photo": IMG["person1"], "country": "Mexico", "city": "Oaxaca",
     "languages": ["Spanish", "English"], "specialties": ["Food", "Markets", "Craft"],
     "bio": "Market and kitchen host supporting family producers and small makers.",
     "price_per_hour": 18, "phone": "+52 951-123-4567", "rating": 4.9, "reviews": 73, "verified": 1,
     "earnings_note": "Food walks & workshops", "experiences": ["exp-12", "exp-13"]},
    {"id": "g7", "name": "Fatima Zahra", "photo": IMG["person2"], "country": "Morocco", "city": "Atlas foothills",
     "languages": ["Arabic", "French", "English"], "specialties": ["Villages", "Craft", "Mountains"],
     "bio": "Village host focused on respectful visits and fair payment to local families.",
     "price_per_hour": 16, "phone": "+212 661-234567", "rating": 4.85, "reviews": 49, "verified": 1,
     "earnings_note": "Village days & weaving", "experiences": ["exp-14", "exp-15"]},
    {"id": "g8", "name": "Amina Benali", "photo": IMG["person4"], "country": "Morocco", "city": "Marrakech region",
     "languages": ["Arabic", "French", "English"], "specialties": ["Food", "Souks", "Culture"],
     "bio": "Food-focused host who avoids peak-hour souks and supports small eateries.",
     "price_per_hour": 15, "phone": "+212 661-234568", "rating": 4.8, "reviews": 58, "verified": 1,
     "earnings_note": "Food walks & village days", "experiences": ["exp-16", "exp-17"]},
    {"id": "g9", "name": "José Quispe", "photo": IMG["person1"], "country": "Peru", "city": "Cusco region",
     "languages": ["Spanish", "Quechua", "English"], "specialties": ["Weaving", "Andes", "Community"],
     "bio": "Connects travelers with Quechua weaving circles so income stays with artisans.",
     "price_per_hour": 16, "phone": "+51 984-123-456", "rating": 4.95, "reviews": 44, "verified": 1,
     "earnings_note": "Weaving circles & valley walks", "experiences": ["exp-21"]},
    {"id": "g10", "name": "Giulia Rossi", "photo": IMG["person6"], "country": "Italy", "city": "Chianti",
     "languages": ["Italian", "English"], "specialties": ["Farm", "Olive oil", "Food"],
     "bio": "Family olive farm host. Small groups only — away from mass Florence tours.",
     "price_per_hour": 25, "phone": "+39 333-123-4567", "rating": 4.9, "reviews": 71, "verified": 1,
     "earnings_note": "Farm mornings & tastings", "experiences": ["exp-23"]},
    {"id": "g11", "name": "Somchai Phan", "photo": IMG["person3"], "country": "Thailand", "city": "Chiang Mai",
     "languages": ["Thai", "English"], "specialties": ["Temples", "Culture", "Alms"],
     "bio": "Cultural host for quiet temple mornings and respectful alms participation.",
     "price_per_hour": 12, "phone": "+66 81-234-5678", "rating": 4.85, "reviews": 39, "verified": 1,
     "earnings_note": "Temple & culture walks", "experiences": ["exp-24"]},
    {"id": "g12", "name": "Ketut Adi", "photo": IMG["person5"], "country": "Indonesia", "city": "Nusa Ceningan",
     "languages": ["Indonesian", "English"], "specialties": ["Coast", "Snorkel", "Conservation"],
     "bio": "Island guide linked to a local marine NGO. Quiet coves over crowded beaches.",
     "price_per_hour": 18, "phone": "+62 812-3456-1012", "rating": 4.8, "reviews": 52, "verified": 1,
     "earnings_note": "Coastal trails & kayak", "experiences": ["exp-3", "exp-9"]},
]

EXPERIENCES = [
    {"id": "exp-1", "name": "Terraced Rice Field Walk with Local Farmers", "type": "nature",
     "location": "Ubud outskirts", "city": "Ubud", "country": "Indonesia",
     "description": "Walk quiet terraced rice fields with local farmers. Learn traditional irrigation and share a simple on-site meal.",
     "image": IMG["rice"], "price": 18, "duration": "3h", "crowd_level": "low",
     "accessibility": "Moderate walking", "sustainability_score": 92, "local_impact_score": 95,
     "lat": -8.5069, "lng": 115.2625, "tags": ["nature", "culture", "family-friendly"], "guide_id": "g1"},
    {"id": "exp-2", "name": "Family Home Kitchen Class", "type": "food",
     "location": "Ubud village", "city": "Ubud", "country": "Indonesia",
     "description": "Cook and share lunch in a family kitchen. Market visit optional.",
     "image": IMG["cook"], "price": 28, "duration": "4h", "crowd_level": "low",
     "accessibility": "Ground floor", "sustainability_score": 90, "local_impact_score": 96,
     "lat": -8.519, "lng": 115.265, "tags": ["food", "culture", "family-friendly"], "guide_id": "g2"},
    {"id": "exp-3", "name": "Quiet Cove Kayak & Snorkel", "type": "nature",
     "location": "Nusa Ceningan", "city": "Nusa Ceningan", "country": "Indonesia",
     "description": "Paddle to quiet coves with a local marine-aware guide. Avoids busy beaches.",
     "image": IMG["kayak"], "price": 35, "duration": "3.5h", "crowd_level": "low",
     "accessibility": "Requires swimming ability", "sustainability_score": 88, "local_impact_score": 85,
     "lat": -8.727, "lng": 115.44, "tags": ["nature", "adventure"], "guide_id": "g12"},
    {"id": "exp-4", "name": "Sunrise Ganges Walk & Quiet Practice", "type": "culture",
     "location": "Rishikesh", "city": "Rishikesh", "country": "India",
     "description": "Early morning riverside walk and short guided practice away from main tourist ghats.",
     "image": IMG["india1"], "price": 12, "duration": "2.5h", "crowd_level": "low",
     "accessibility": "Flat paths", "sustainability_score": 91, "local_impact_score": 88,
     "lat": 30.0869, "lng": 78.2676, "tags": ["culture", "wellness", "nature"], "guide_id": "g3"},
    {"id": "exp-5", "name": "Forest Trail & Local Herbal Knowledge", "type": "nature",
     "location": "Rishikesh hills", "city": "Rishikesh", "country": "India",
     "description": "Guided forest walk with a local host sharing plant knowledge and quiet viewpoints.",
     "image": IMG["forest"], "price": 15, "duration": "3h", "crowd_level": "low",
     "accessibility": "Moderate incline", "sustainability_score": 93, "local_impact_score": 90,
     "lat": 30.12, "lng": 78.3, "tags": ["nature", "wellness"], "guide_id": "g3"},
    {"id": "exp-6", "name": "Village Textile & Craft Day", "type": "craft",
     "location": "Near Jaipur", "city": "Jaipur region", "country": "India",
     "description": "Visit artisan families, try simple weaving or block-print, and support local makers directly.",
     "image": IMG["textile"], "price": 22, "duration": "5h", "crowd_level": "low",
     "accessibility": "Seated options", "sustainability_score": 94, "local_impact_score": 97,
     "lat": 26.9, "lng": 75.8, "tags": ["craft", "culture", "family-friendly"], "guide_id": "g4"},
    {"id": "exp-7", "name": "Evening Village Rice Field Stroll", "type": "nature",
     "location": "Ubud outskirts", "city": "Ubud", "country": "Indonesia",
     "description": "Golden-hour walk through quieter fields with a farmer host.",
     "image": IMG["rice"], "price": 14, "duration": "2h", "crowd_level": "low",
     "accessibility": "Moderate walking", "sustainability_score": 90, "local_impact_score": 92,
     "lat": -8.51, "lng": 115.26, "tags": ["nature", "culture"], "guide_id": "g1"},
    {"id": "exp-8", "name": "Morning Market & Spice Kitchen", "type": "food",
     "location": "Ubud", "city": "Ubud", "country": "Indonesia",
     "description": "Early market visit then cook with a family host using local produce.",
     "image": IMG["market"], "price": 30, "duration": "4.5h", "crowd_level": "medium",
     "accessibility": "Ground floor", "sustainability_score": 89, "local_impact_score": 94,
     "lat": -8.506, "lng": 115.262, "tags": ["food", "culture"], "guide_id": "g2"},
    {"id": "exp-9", "name": "Coastal Conservation Walk", "type": "nature",
     "location": "Nusa Ceningan", "city": "Nusa Ceningan", "country": "Indonesia",
     "description": "Coastal trail with a guide linked to a local marine NGO.",
     "image": IMG["beach"], "price": 20, "duration": "2.5h", "crowd_level": "low",
     "accessibility": "Uneven paths", "sustainability_score": 92, "local_impact_score": 90,
     "lat": -8.73, "lng": 115.44, "tags": ["nature", "conservation"], "guide_id": "g12"},
    {"id": "exp-10", "name": "Quiet Temple Garden Morning", "type": "culture",
     "location": "Kyoto outskirts", "city": "Kyoto", "country": "Japan",
     "description": "Early visit to lesser-known temple gardens with a soft-spoken local host.",
     "image": IMG["japan"], "price": 45, "duration": "3h", "crowd_level": "low",
     "accessibility": "Some steps", "sustainability_score": 88, "local_impact_score": 85,
     "lat": 35.01, "lng": 135.78, "tags": ["culture", "wellness"], "guide_id": "g5"},
    {"id": "exp-11", "name": "Tea & Quiet Path Walk", "type": "culture",
     "location": "Kyoto outskirts", "city": "Kyoto", "country": "Japan",
     "description": "Gentle walk and tea with a local host away from main tourist routes.",
     "image": IMG["foodjp"], "price": 38, "duration": "2.5h", "crowd_level": "low",
     "accessibility": "Mostly flat", "sustainability_score": 90, "local_impact_score": 87,
     "lat": 35.02, "lng": 135.79, "tags": ["culture", "food"], "guide_id": "g5"},
    {"id": "exp-12", "name": "Oaxaca Market Food Walk", "type": "food",
     "location": "Oaxaca", "city": "Oaxaca", "country": "Mexico",
     "description": "Taste local specialties with a host who supports family producers.",
     "image": IMG["mexico"], "price": 25, "duration": "3h", "crowd_level": "medium",
     "accessibility": "Walking", "sustainability_score": 87, "local_impact_score": 93,
     "lat": 17.07, "lng": -96.72, "tags": ["food", "culture"], "guide_id": "g6"},
    {"id": "exp-13", "name": "Clay & Textile Workshop", "type": "craft",
     "location": "Oaxaca region", "city": "Oaxaca", "country": "Mexico",
     "description": "Hands-on session with local makers; income stays with the artisans.",
     "image": IMG["craft"], "price": 32, "duration": "4h", "crowd_level": "low",
     "accessibility": "Seated options", "sustainability_score": 94, "local_impact_score": 96,
     "lat": 17.08, "lng": -96.7, "tags": ["craft", "culture"], "guide_id": "g6"},
    {"id": "exp-14", "name": "Atlas Foothills Village Day", "type": "culture",
     "location": "Atlas foothills", "city": "Atlas", "country": "Morocco",
     "description": "Respectful village visit with fair payment to host families.",
     "image": IMG["atlas"], "price": 28, "duration": "6h", "crowd_level": "low",
     "accessibility": "Uneven paths", "sustainability_score": 91, "local_impact_score": 95,
     "lat": 31.1, "lng": -7.9, "tags": ["culture", "nature"], "guide_id": "g7"},
    {"id": "exp-15", "name": "Weaving Circle Visit", "type": "craft",
     "location": "Atlas foothills", "city": "Atlas", "country": "Morocco",
     "description": "Meet weavers and support their work directly.",
     "image": IMG["weave"], "price": 22, "duration": "3h", "crowd_level": "low",
     "accessibility": "Seated", "sustainability_score": 93, "local_impact_score": 97,
     "lat": 31.12, "lng": -7.88, "tags": ["craft", "culture"], "guide_id": "g7"},
    {"id": "exp-16", "name": "Quiet Food Walk (Off-peak Souks)", "type": "food",
     "location": "Marrakech region", "city": "Marrakech", "country": "Morocco",
     "description": "Taste local dishes with a host who avoids peak-hour crowds.",
     "image": IMG["morocco"], "price": 24, "duration": "3h", "crowd_level": "medium",
     "accessibility": "Walking", "sustainability_score": 86, "local_impact_score": 90,
     "lat": 31.63, "lng": -8.0, "tags": ["food", "culture"], "guide_id": "g8"},
    {"id": "exp-17", "name": "Village Kitchen Lunch", "type": "food",
     "location": "Near Marrakech", "city": "Marrakech", "country": "Morocco",
     "description": "Home-style lunch with a local family host.",
     "image": IMG["dinner"], "price": 20, "duration": "2.5h", "crowd_level": "low",
     "accessibility": "Ground level", "sustainability_score": 92, "local_impact_score": 94,
     "lat": 31.65, "lng": -7.95, "tags": ["food", "culture", "family-friendly"], "guide_id": "g8"},
    {"id": "exp-19", "name": "Artisan Block-Print Workshop", "type": "craft",
     "location": "Near Jaipur", "city": "Jaipur region", "country": "India",
     "description": "Hands-on block printing with a local maker family.",
     "image": IMG["india2"], "price": 26, "duration": "3.5h", "crowd_level": "low",
     "accessibility": "Seated", "sustainability_score": 93, "local_impact_score": 96,
     "lat": 26.91, "lng": 75.82, "tags": ["craft", "culture"], "guide_id": "g4"},
    {"id": "exp-20", "name": "Village Morning Market Trail", "type": "food",
     "location": "Near Jaipur", "city": "Jaipur region", "country": "India",
     "description": "Early market visit with a local host supporting small vendors.",
     "image": IMG["india3"], "price": 14, "duration": "2.5h", "crowd_level": "medium",
     "accessibility": "Walking", "sustainability_score": 88, "local_impact_score": 91,
     "lat": 26.92, "lng": 75.81, "tags": ["food", "culture"], "guide_id": "g4"},
    {"id": "exp-21", "name": "Quechua Weaving Circle", "type": "craft",
     "location": "Cusco region", "city": "Cusco", "country": "Peru",
     "description": "Meet weaving artisans and support their work directly.",
     "image": IMG["peru"], "price": 30, "duration": "4h", "crowd_level": "low",
     "accessibility": "Seated options", "sustainability_score": 95, "local_impact_score": 98,
     "lat": -13.5, "lng": -71.97, "tags": ["craft", "culture", "community"], "guide_id": "g9"},
    {"id": "exp-23", "name": "Olive Farm Morning & Tasting", "type": "food",
     "location": "Chianti", "city": "Chianti", "country": "Italy",
     "description": "Family olive farm visit with tasting. Small groups only.",
     "image": IMG["tuscany"], "price": 48, "duration": "3.5h", "crowd_level": "low",
     "accessibility": "Farm paths", "sustainability_score": 90, "local_impact_score": 94,
     "lat": 43.4, "lng": 11.3, "tags": ["food", "farm", "nature"], "guide_id": "g10"},
    {"id": "exp-24", "name": "Quiet Temple Morning & Alms", "type": "culture",
     "location": "Chiang Mai", "city": "Chiang Mai", "country": "Thailand",
     "description": "Respectful early temple visit and cultural context with a local host.",
     "image": IMG["thailand"], "price": 18, "duration": "2.5h", "crowd_level": "low",
     "accessibility": "Some steps", "sustainability_score": 89, "local_impact_score": 86,
     "lat": 18.79, "lng": 98.98, "tags": ["culture", "temples"], "guide_id": "g11"},
]


def seed():
    if os.path.exists(DB_PATH):
        os.remove(DB_PATH)
    init_db()
    with db_cursor() as cur:
        # demo user
        cur.execute(
            "INSERT INTO users (email, password_hash, name, role, preferred_lang) VALUES (?, ?, ?, ?, ?)",
            ("demo@roamlocal.com", "demo123", "Demo Traveler", "traveler", "en"),
        )
        for g in GUIDES:
            cur.execute(
                """INSERT INTO guides (id, name, photo, country, city, languages, specialties, bio,
                   price_per_hour, rating, reviews, verified, earnings_note, experiences, phone)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    g["id"], g["name"], g["photo"], g["country"], g["city"],
                    json.dumps(g["languages"]), json.dumps(g["specialties"]), g["bio"],
                    g["price_per_hour"], g["rating"], g["reviews"], g["verified"],
                    g["earnings_note"], json.dumps(g["experiences"]), g.get("phone", ""),
                ),
            )
        for e in EXPERIENCES:
            cur.execute(
                """INSERT INTO experiences (id, name, type, location, city, country, description,
                   image, price, duration, crowd_level, accessibility, sustainability_score,
                   local_impact_score, lat, lng, tags, guide_id)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    e["id"], e["name"], e["type"], e["location"], e["city"], e["country"],
                    e["description"], e["image"], e["price"], e["duration"], e["crowd_level"],
                    e["accessibility"], e["sustainability_score"], e["local_impact_score"],
                    e["lat"], e["lng"], json.dumps(e["tags"]), e.get("guide_id"),
                ),
            )
    print(f"Seeded {len(GUIDES)} guides and {len(EXPERIENCES)} experiences.")


if __name__ == "__main__":
    seed()
